data:
  data_file: "/Users/ashoksharma/Local_Folder/pythonfiles/sea-reproduce/data/hepar2/hepar2.csv"  # <- set your actual CSV path. [web:1]
  debug: False
  batch_size: 1
  fci_vars: 5
  fci_batches: 10
  fci_batches_inference: 500
  fci_batch_size: 500
  envs_per_batch: 5
  num_workers: 4                     # reduce on macOS if high. [web:1]
  accumulate_batches: 1
  log_frequency: 10
  results_file: "outputs/hepar2_run/result.pkl"  # <- new output location. [web:1]

model:
  algorithm: "gies"
  model: "aggregator"
  num_vars: 70                       # <- HEPAR2 variable count. [web:7]
  num_edge_types: 5
  embed_dim: 64
  transformer_num_layers: 4
  n_heads: 8
  ffn_embed_dim: 8
  use_learned_sampler: False

train:
  run_name: sc-rl
  patience: 50
  epochs: 10000
  min_epochs: 50
  lr: 1.e-4
  weight_decay: 1.e-5
  metric: "Val/auprc"
